# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emamy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  #react-native-image-crop
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]


  # very important to have, unless you removed React dependencies for Libraries 
  # and you rely on Cocoapods to manage it
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
  #end of react-native-image-crop

  # Pods for emamy

  target 'emamy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emamyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end